# Generated by Django 3.0.8 on 2020-08-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_sendback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendBack',
        ),
    ]
