# Generated by Django 3.0.8 on 2020-07-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
