# Generated by Django 3.0.8 on 2020-08-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200819_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='In Progress', max_length=100),
        ),
    ]
