# Generated by Django 3.0.8 on 2020-08-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200812_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2_url',
        ),
    ]
