# Generated by Django 3.0.8 on 2020-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200812_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image2_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
