# Generated by Django 3.0.8 on 2020-08-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200812_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2_url',
        ),
    ]
